package model.db;
// Generated 18/01/2017 03:23:27 PM by Hibernate Tools 3.2.2.GA



/**
 * WmbBustransId generated by hbm2java
 */
public class WmbBustransId  implements java.io.Serializable {


     private String id;
     private String btdName;
     private int seqNo;

    public WmbBustransId() {
    }

    public WmbBustransId(String id, String btdName, int seqNo) {
       this.id = id;
       this.btdName = btdName;
       this.seqNo = seqNo;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getBtdName() {
        return this.btdName;
    }
    
    public void setBtdName(String btdName) {
        this.btdName = btdName;
    }
    public int getSeqNo() {
        return this.seqNo;
    }
    
    public void setSeqNo(int seqNo) {
        this.seqNo = seqNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WmbBustransId) ) return false;
		 WmbBustransId castOther = ( WmbBustransId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getBtdName()==castOther.getBtdName()) || ( this.getBtdName()!=null && castOther.getBtdName()!=null && this.getBtdName().equals(castOther.getBtdName()) ) )
 && (this.getSeqNo()==castOther.getSeqNo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getBtdName() == null ? 0 : this.getBtdName().hashCode() );
         result = 37 * result + this.getSeqNo();
         return result;
   }   


}


