package model.db;
// Generated 18/01/2017 03:23:27 PM by Hibernate Tools 3.2.2.GA


import java.io.Serializable;
import java.sql.Clob;

/**
 * WmbBinaryData generated by hbm2java
 */
public class WmbBinaryData  implements java.io.Serializable {


     private WmbBinaryDataId id;
     private String encoding;
     private Clob data;
     private Serializable db2GeneratedRowidForLobs;

    public WmbBinaryData() {
    }

	
    public WmbBinaryData(WmbBinaryDataId id, String encoding, Serializable db2GeneratedRowidForLobs) {
        this.id = id;
        this.encoding = encoding;
        this.db2GeneratedRowidForLobs = db2GeneratedRowidForLobs;
    }
    public WmbBinaryData(WmbBinaryDataId id, String encoding, Clob data, Serializable db2GeneratedRowidForLobs) {
       this.id = id;
       this.encoding = encoding;
       this.data = data;
       this.db2GeneratedRowidForLobs = db2GeneratedRowidForLobs;
    }
   
    public WmbBinaryDataId getId() {
        return this.id;
    }
    
    public void setId(WmbBinaryDataId id) {
        this.id = id;
    }
    public String getEncoding() {
        return this.encoding;
    }
    
    public void setEncoding(String encoding) {
        this.encoding = encoding;
    }
    public Clob getData() {
        return this.data;
    }
    
    public void setData(Clob data) {
        this.data = data;
    }
    public Serializable getDb2GeneratedRowidForLobs() {
        return this.db2GeneratedRowidForLobs;
    }
    
    public void setDb2GeneratedRowidForLobs(Serializable db2GeneratedRowidForLobs) {
        this.db2GeneratedRowidForLobs = db2GeneratedRowidForLobs;
    }




}


