package model.db;
// Generated 18/01/2017 03:23:27 PM by Hibernate Tools 3.2.2.GA



/**
 * WmbBinaryDataId generated by hbm2java
 */
public class WmbBinaryDataId  implements java.io.Serializable {


     private String wmbMsgkey;
     private int dataType;

    public WmbBinaryDataId() {
    }

    public WmbBinaryDataId(String wmbMsgkey, int dataType) {
       this.wmbMsgkey = wmbMsgkey;
       this.dataType = dataType;
    }
   
    public String getWmbMsgkey() {
        return this.wmbMsgkey;
    }
    
    public void setWmbMsgkey(String wmbMsgkey) {
        this.wmbMsgkey = wmbMsgkey;
    }
    public int getDataType() {
        return this.dataType;
    }
    
    public void setDataType(int dataType) {
        this.dataType = dataType;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WmbBinaryDataId) ) return false;
		 WmbBinaryDataId castOther = ( WmbBinaryDataId ) other; 
         
		 return ( (this.getWmbMsgkey()==castOther.getWmbMsgkey()) || ( this.getWmbMsgkey()!=null && castOther.getWmbMsgkey()!=null && this.getWmbMsgkey().equals(castOther.getWmbMsgkey()) ) )
 && (this.getDataType()==castOther.getDataType());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getWmbMsgkey() == null ? 0 : this.getWmbMsgkey().hashCode() );
         result = 37 * result + this.getDataType();
         return result;
   }   


}


