package model.db;
// Generated 18/01/2017 03:23:27 PM by Hibernate Tools 3.2.2.GA



/**
 * WmbBustrans generated by hbm2java
 */
public class WmbBustrans  implements java.io.Serializable {


     private WmbBustransId id;
     private String firstSeenTimestamp;
     private String lastSeenTimestamp;
     private Character status;
     private String wmbMsgkey;
     private Long seqTime;
     private Integer role;
     private String uniqueFlowName;

    public WmbBustrans() {
    }

	
    public WmbBustrans(WmbBustransId id, String wmbMsgkey) {
        this.id = id;
        this.wmbMsgkey = wmbMsgkey;
    }
    public WmbBustrans(WmbBustransId id, String firstSeenTimestamp, String lastSeenTimestamp, Character status, String wmbMsgkey, Long seqTime, Integer role, String uniqueFlowName) {
       this.id = id;
       this.firstSeenTimestamp = firstSeenTimestamp;
       this.lastSeenTimestamp = lastSeenTimestamp;
       this.status = status;
       this.wmbMsgkey = wmbMsgkey;
       this.seqTime = seqTime;
       this.role = role;
       this.uniqueFlowName = uniqueFlowName;
    }
   
    public WmbBustransId getId() {
        return this.id;
    }
    
    public void setId(WmbBustransId id) {
        this.id = id;
    }
    public String getFirstSeenTimestamp() {
        return this.firstSeenTimestamp;
    }
    
    public void setFirstSeenTimestamp(String firstSeenTimestamp) {
        this.firstSeenTimestamp = firstSeenTimestamp;
    }
    public String getLastSeenTimestamp() {
        return this.lastSeenTimestamp;
    }
    
    public void setLastSeenTimestamp(String lastSeenTimestamp) {
        this.lastSeenTimestamp = lastSeenTimestamp;
    }
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }
    public String getWmbMsgkey() {
        return this.wmbMsgkey;
    }
    
    public void setWmbMsgkey(String wmbMsgkey) {
        this.wmbMsgkey = wmbMsgkey;
    }
    public Long getSeqTime() {
        return this.seqTime;
    }
    
    public void setSeqTime(Long seqTime) {
        this.seqTime = seqTime;
    }
    public Integer getRole() {
        return this.role;
    }
    
    public void setRole(Integer role) {
        this.role = role;
    }
    public String getUniqueFlowName() {
        return this.uniqueFlowName;
    }
    
    public void setUniqueFlowName(String uniqueFlowName) {
        this.uniqueFlowName = uniqueFlowName;
    }




}


