package model.db;
// Generated 18/01/2017 03:23:27 PM by Hibernate Tools 3.2.2.GA



/**
 * WmbEventTypes generated by hbm2java
 */
public class WmbEventTypes  implements java.io.Serializable {


     private int eventTypeId;
     private String eventName;
     private String eventDescription;

    public WmbEventTypes() {
    }

	
    public WmbEventTypes(int eventTypeId) {
        this.eventTypeId = eventTypeId;
    }
    public WmbEventTypes(int eventTypeId, String eventName, String eventDescription) {
       this.eventTypeId = eventTypeId;
       this.eventName = eventName;
       this.eventDescription = eventDescription;
    }
   
    public int getEventTypeId() {
        return this.eventTypeId;
    }
    
    public void setEventTypeId(int eventTypeId) {
        this.eventTypeId = eventTypeId;
    }
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }
    public String getEventDescription() {
        return this.eventDescription;
    }
    
    public void setEventDescription(String eventDescription) {
        this.eventDescription = eventDescription;
    }




}


