package model.db;
// Generated 18/01/2017 03:23:27 PM by Hibernate Tools 3.2.2.GA



/**
 * WmbMsgs generated by hbm2java
 */
public class WmbMsgs  implements java.io.Serializable {


     private String wmbMsgkey;
     private Character hasBitstream;
     private Character hasException;
     private Character hasUserdata;
     private String eventType;
     private String eventName;
     private String eventSrcaddr;
     private String brokerName;
     private String brokerUuid;
     private String exgrpName;
     private String exgrpUuid;
     private String msgflowName;
     private String msgflowUuid;
     private String applName;
     private String applUuid;
     private String libraryName;
     private String libraryUuid;
     private String nodeName;
     private String nodeType;
     private String detail;
     private String terminalName;
     private String keyFld1Nm;
     private String keyFld2Nm;
     private String keyFld3Nm;
     private String keyFld4Nm;
     private String keyFld5Nm;
     private String eventTimestamp;
     private String localTransactionId;
     private String parentTransactionId;
     private String globalTransactionId;

    public WmbMsgs() {
    }

	
    public WmbMsgs(String wmbMsgkey) {
        this.wmbMsgkey = wmbMsgkey;
    }
    public WmbMsgs(String wmbMsgkey, Character hasBitstream, Character hasException, Character hasUserdata, String eventType, String eventName, String eventSrcaddr, String brokerName, String brokerUuid, String exgrpName, String exgrpUuid, String msgflowName, String msgflowUuid, String applName, String applUuid, String libraryName, String libraryUuid, String nodeName, String nodeType, String detail, String terminalName, String keyFld1Nm, String keyFld2Nm, String keyFld3Nm, String keyFld4Nm, String keyFld5Nm, String eventTimestamp, String localTransactionId, String parentTransactionId, String globalTransactionId) {
       this.wmbMsgkey = wmbMsgkey;
       this.hasBitstream = hasBitstream;
       this.hasException = hasException;
       this.hasUserdata = hasUserdata;
       this.eventType = eventType;
       this.eventName = eventName;
       this.eventSrcaddr = eventSrcaddr;
       this.brokerName = brokerName;
       this.brokerUuid = brokerUuid;
       this.exgrpName = exgrpName;
       this.exgrpUuid = exgrpUuid;
       this.msgflowName = msgflowName;
       this.msgflowUuid = msgflowUuid;
       this.applName = applName;
       this.applUuid = applUuid;
       this.libraryName = libraryName;
       this.libraryUuid = libraryUuid;
       this.nodeName = nodeName;
       this.nodeType = nodeType;
       this.detail = detail;
       this.terminalName = terminalName;
       this.keyFld1Nm = keyFld1Nm;
       this.keyFld2Nm = keyFld2Nm;
       this.keyFld3Nm = keyFld3Nm;
       this.keyFld4Nm = keyFld4Nm;
       this.keyFld5Nm = keyFld5Nm;
       this.eventTimestamp = eventTimestamp;
       this.localTransactionId = localTransactionId;
       this.parentTransactionId = parentTransactionId;
       this.globalTransactionId = globalTransactionId;
    }
   
    public String getWmbMsgkey() {
        return this.wmbMsgkey;
    }
    
    public void setWmbMsgkey(String wmbMsgkey) {
        this.wmbMsgkey = wmbMsgkey;
    }
    public Character getHasBitstream() {
        return this.hasBitstream;
    }
    
    public void setHasBitstream(Character hasBitstream) {
        this.hasBitstream = hasBitstream;
    }
    public Character getHasException() {
        return this.hasException;
    }
    
    public void setHasException(Character hasException) {
        this.hasException = hasException;
    }
    public Character getHasUserdata() {
        return this.hasUserdata;
    }
    
    public void setHasUserdata(Character hasUserdata) {
        this.hasUserdata = hasUserdata;
    }
    public String getEventType() {
        return this.eventType;
    }
    
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }
    public String getEventSrcaddr() {
        return this.eventSrcaddr;
    }
    
    public void setEventSrcaddr(String eventSrcaddr) {
        this.eventSrcaddr = eventSrcaddr;
    }
    public String getBrokerName() {
        return this.brokerName;
    }
    
    public void setBrokerName(String brokerName) {
        this.brokerName = brokerName;
    }
    public String getBrokerUuid() {
        return this.brokerUuid;
    }
    
    public void setBrokerUuid(String brokerUuid) {
        this.brokerUuid = brokerUuid;
    }
    public String getExgrpName() {
        return this.exgrpName;
    }
    
    public void setExgrpName(String exgrpName) {
        this.exgrpName = exgrpName;
    }
    public String getExgrpUuid() {
        return this.exgrpUuid;
    }
    
    public void setExgrpUuid(String exgrpUuid) {
        this.exgrpUuid = exgrpUuid;
    }
    public String getMsgflowName() {
        return this.msgflowName;
    }
    
    public void setMsgflowName(String msgflowName) {
        this.msgflowName = msgflowName;
    }
    public String getMsgflowUuid() {
        return this.msgflowUuid;
    }
    
    public void setMsgflowUuid(String msgflowUuid) {
        this.msgflowUuid = msgflowUuid;
    }
    public String getApplName() {
        return this.applName;
    }
    
    public void setApplName(String applName) {
        this.applName = applName;
    }
    public String getApplUuid() {
        return this.applUuid;
    }
    
    public void setApplUuid(String applUuid) {
        this.applUuid = applUuid;
    }
    public String getLibraryName() {
        return this.libraryName;
    }
    
    public void setLibraryName(String libraryName) {
        this.libraryName = libraryName;
    }
    public String getLibraryUuid() {
        return this.libraryUuid;
    }
    
    public void setLibraryUuid(String libraryUuid) {
        this.libraryUuid = libraryUuid;
    }
    public String getNodeName() {
        return this.nodeName;
    }
    
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }
    public String getNodeType() {
        return this.nodeType;
    }
    
    public void setNodeType(String nodeType) {
        this.nodeType = nodeType;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public String getTerminalName() {
        return this.terminalName;
    }
    
    public void setTerminalName(String terminalName) {
        this.terminalName = terminalName;
    }
    public String getKeyFld1Nm() {
        return this.keyFld1Nm;
    }
    
    public void setKeyFld1Nm(String keyFld1Nm) {
        this.keyFld1Nm = keyFld1Nm;
    }
    public String getKeyFld2Nm() {
        return this.keyFld2Nm;
    }
    
    public void setKeyFld2Nm(String keyFld2Nm) {
        this.keyFld2Nm = keyFld2Nm;
    }
    public String getKeyFld3Nm() {
        return this.keyFld3Nm;
    }
    
    public void setKeyFld3Nm(String keyFld3Nm) {
        this.keyFld3Nm = keyFld3Nm;
    }
    public String getKeyFld4Nm() {
        return this.keyFld4Nm;
    }
    
    public void setKeyFld4Nm(String keyFld4Nm) {
        this.keyFld4Nm = keyFld4Nm;
    }
    public String getKeyFld5Nm() {
        return this.keyFld5Nm;
    }
    
    public void setKeyFld5Nm(String keyFld5Nm) {
        this.keyFld5Nm = keyFld5Nm;
    }
    public String getEventTimestamp() {
        return this.eventTimestamp;
    }
    
    public void setEventTimestamp(String eventTimestamp) {
        this.eventTimestamp = eventTimestamp;
    }
    public String getLocalTransactionId() {
        return this.localTransactionId;
    }
    
    public void setLocalTransactionId(String localTransactionId) {
        this.localTransactionId = localTransactionId;
    }
    public String getParentTransactionId() {
        return this.parentTransactionId;
    }
    
    public void setParentTransactionId(String parentTransactionId) {
        this.parentTransactionId = parentTransactionId;
    }
    public String getGlobalTransactionId() {
        return this.globalTransactionId;
    }
    
    public void setGlobalTransactionId(String globalTransactionId) {
        this.globalTransactionId = globalTransactionId;
    }




}


