package model.db;
// Generated 18/01/2017 03:23:27 PM by Hibernate Tools 3.2.2.GA



/**
 * WmbTest generated by hbm2java
 */
public class WmbTest  implements java.io.Serializable {


     private WmbTestId id;

    public WmbTest() {
    }

    public WmbTest(WmbTestId id) {
       this.id = id;
    }
   
    public WmbTestId getId() {
        return this.id;
    }
    
    public void setId(WmbTestId id) {
        this.id = id;
    }




}


