package model.db;
// Generated 18/01/2017 03:23:27 PM by Hibernate Tools 3.2.2.GA



/**
 * WmbTestId generated by hbm2java
 */
public class WmbTestId  implements java.io.Serializable {


     private int id;
     private String data;

    public WmbTestId() {
    }

	
    public WmbTestId(int id) {
        this.id = id;
    }
    public WmbTestId(int id, String data) {
       this.id = id;
       this.data = data;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WmbTestId) ) return false;
		 WmbTestId castOther = ( WmbTestId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getData()==castOther.getData()) || ( this.getData()!=null && castOther.getData()!=null && this.getData().equals(castOther.getData()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getData() == null ? 0 : this.getData().hashCode() );
         return result;
   }   


}


